### ISSUE TITLE
Token Auth for Azure SQL Server to Store ASP.NET Session State

### ISSUE THREAD

**Issue by c767695** [aspnet/AspNetSessionState#22]
Is there a feature in the roadmap already for in the roadmap to implement a layer to allow developers to use Azure SQL token authorization for the Sql Provider to store the ASP.NET Session State? Are there other providers for Azure that fill a similar role such as Azure Cache for Redis.

**Comment by c767695** [comment]
Thanks, please do.

**Comment by ajepst** [comment]
Any progress on this? 

Connecting via token is current best practice, and especially helpful in environments with password rotation requirements. Core seems like it's pretty thoroughly implemented tokens at this point, but those of us supporting older projects may not be able to move off the older framework without a large upgrade effort (which, yes, needs to happen, but might not be in the near future)

**Comment by janecosham** [comment]
I'd also like to know the state here. I'm in the process of switching our ASP.NET application to use Microsoft.Data.SqlClient rather than System.Data.SqlClient to get the ability to use the token auth with just a connection string change (using "Authentication=Active Directory Managed Identity") but this is causing issues with session state since it uses System.Data.SqlClient which doesn't have this option.

**Comment by janecosham** [comment]
Any update here?

**Comment by johnayoub** [comment]
@davidfowl any update to switch to Microsoft.Data.SqlClient to support managed identity authentication?

**Comment by johnayoub** [comment]
@Jinhuafei Any plans to maintain this package?

**Comment by Jinhuafei** [comment]
CC @StephenMolloy @HongGit
