### ISSUE TITLE
Allow using provisioned throughput

### ISSUE THREAD

**Issue by ghost** [aspnet/AspNetSessionState#32]
I want to be able to deploy multiple copies of my application, all using the same Cosmos DB with provisioned and shared throughput.

Currently I'm getting "_[DocumentClientException]: Provisioned throughput collection should have a partition key_" if I try to point the config to a DB with provisioned throughput.

**Comment by StephenMolloy** [comment]
Unfortunately, by default, the cosmos provider does not configure itself to take advantage of partitioning. And for compatibility, we cannot update the default behavior.

You can opt in to recommended partitioning behavior quite easily though. On your cosmos provider declaration in config, set these two options - partitionKey="pKey" partitionNumUsedByProvider="*" - and you're good to go. You will get the maximum number of partitions, which is ok because partitioning is free in cosmos. And the more partitions you have, the easier it is to leverage and scale using Cosmos DB's provisioning controls.

**Comment by obaymar** [comment]
Hi Stephen,

Thank you for your response. I'm afraid I'm just not properly understanding the use model of the Cosmos DB provider.

What I need to accomplish is the ability to have a fixed cost of a multi-app deployment (think of a k8s cluster with dozens of versions of an app using the provider), with the ability to clearly identify data entries which belong to a given app for cleanup, debug or security regulation purpose.

I thought I'd be able to accomplish that by giving each app their own collection on a provisioned throughput DB, but alas it's not possible. I either need to create separately provisioned collections (way to expensive) or have all the apps use the same collection (but then I'm not sure how to configure individual apps to tell their records apart).

What is the way to accomplish my goal?

Also, I'm not quite sure I have the partition key work properly. Regardless of the value ("pKey" or anything else), the newly created collection has "_partitionKey" key, which is empty for all the records (see the [screenshot](https://photos.app.goo.gl/rdLi61dW7KeLB5DMA).

**Comment by ai2admin** [comment]
Submitted a PR.

**Comment by StephenMolloy** [comment]
Merged #68 (Guided by #33)
